site_name: Camel Code
site_url: https://CamelCode.github.io/
# === Custom Theme === #
theme:
  name: material
  # === Blog palette === #
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  # === Custom nav feature === #
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - navigation.prune
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.annotate
    # - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tree-1917
      name: github
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/gamalmoussa1917/
      name: linkedin

copyright: Copyright &copy; 2024 - 2025 Gamal Moussa

# === plugins === #
plugins:
  - search
  # - tags:
  #     tags_file: tags.md
  # - blog

# === code blocks === #
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
# === custom css === #
extra_css:
  - assets/stylesheets/extra.css
# # === custom js === #
# extra_javascript:
#   - assets/javascripts/extra.js
